// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: recordfanout.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FanoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId int32 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
}

func (x *FanoutRequest) Reset() {
	*x = FanoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordfanout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FanoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanoutRequest) ProtoMessage() {}

func (x *FanoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recordfanout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanoutRequest.ProtoReflect.Descriptor instead.
func (*FanoutRequest) Descriptor() ([]byte, []int) {
	return file_recordfanout_proto_rawDescGZIP(), []int{0}
}

func (x *FanoutRequest) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type FanoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FanoutResponse) Reset() {
	*x = FanoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordfanout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FanoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanoutResponse) ProtoMessage() {}

func (x *FanoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recordfanout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanoutResponse.ProtoReflect.Descriptor instead.
func (*FanoutResponse) Descriptor() ([]byte, []int) {
	return file_recordfanout_proto_rawDescGZIP(), []int{1}
}

var File_recordfanout_proto protoreflect.FileDescriptor

var file_recordfanout_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x66, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x66, 0x61, 0x6e, 0x6f,
	0x75, 0x74, 0x22, 0x30, 0x0a, 0x0d, 0x46, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x46, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x5c, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x46, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a,
	0x06, 0x46, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x12, 0x1b, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x66, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x2e, 0x46, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x66, 0x61, 0x6e,
	0x6f, 0x75, 0x74, 0x2e, 0x46, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x66, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recordfanout_proto_rawDescOnce sync.Once
	file_recordfanout_proto_rawDescData = file_recordfanout_proto_rawDesc
)

func file_recordfanout_proto_rawDescGZIP() []byte {
	file_recordfanout_proto_rawDescOnce.Do(func() {
		file_recordfanout_proto_rawDescData = protoimpl.X.CompressGZIP(file_recordfanout_proto_rawDescData)
	})
	return file_recordfanout_proto_rawDescData
}

var file_recordfanout_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recordfanout_proto_goTypes = []interface{}{
	(*FanoutRequest)(nil),  // 0: recordfanout.FanoutRequest
	(*FanoutResponse)(nil), // 1: recordfanout.FanoutResponse
}
var file_recordfanout_proto_depIdxs = []int32{
	0, // 0: recordfanout.RecordFanoutService.Fanout:input_type -> recordfanout.FanoutRequest
	1, // 1: recordfanout.RecordFanoutService.Fanout:output_type -> recordfanout.FanoutResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_recordfanout_proto_init() }
func file_recordfanout_proto_init() {
	if File_recordfanout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recordfanout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FanoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordfanout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FanoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recordfanout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recordfanout_proto_goTypes,
		DependencyIndexes: file_recordfanout_proto_depIdxs,
		MessageInfos:      file_recordfanout_proto_msgTypes,
	}.Build()
	File_recordfanout_proto = out.File
	file_recordfanout_proto_rawDesc = nil
	file_recordfanout_proto_goTypes = nil
	file_recordfanout_proto_depIdxs = nil
}
